server.port=8081

spring.datasource.url=jdbc:sqlite:tags.db
spring.datasource.driver-class-name=org.sqlite.JDBC

mybatis.mapper-locations=mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
