"""Evidence pack report generation (Markdown + HTML)."""

from __future__ import annotations

from datetime import datetime

from .models import EvidencePack


def generate_markdown_report(pack: EvidencePack) -> str:
    lines: list[str] = []
    lines.append(f"# Competitor Intelligence Evidence Pack")
    lines.append(f"**Generated:** {pack.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if pack.completed_at:
        lines.append(f"**Completed:** {pack.completed_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Status:** {pack.status.value}")
    lines.append(f"**Coverage Score:** {pack.coverage_score:.1f}%")
    lines.append("")

    # Competitors
    lines.append("## Competitors Analyzed")
    for comp in pack.competitors:
        url_part = f" — [{comp.url}]({comp.url})" if comp.url else ""
        lines.append(f"- **{comp.name}**{url_part}")
    lines.append("")

    # Research iterations
    if pack.iterations:
        lines.append("## Research Iterations")
        for it in pack.iterations:
            lines.append(
                f"- **Iteration {it.iteration}**: Found {len(it.gaps_found)} gaps, "
                f"added {it.evidence_added} evidence items, "
                f"resolved {it.gaps_resolved} gaps"
            )
        lines.append("")

    # Evidence by competitor
    lines.append("## Evidence by Competitor")
    for comp_name, items in pack.evidence_by_competitor.items():
        lines.append(f"### {comp_name}")
        lines.append(f"*{len(items)} evidence items collected*")
        lines.append("")
        for item in items:
            confidence_icon = {"high": "🟢", "medium": "🟡", "low": "🔴"}.get(
                item.confidence.value, "⚪"
            )
            lines.append(
                f"#### [{item.category.value.upper()}] {confidence_icon} {item.claim}"
            )
            lines.append(f"> {item.supporting_text[:500]}")
            if item.citations:
                for cit in item.citations:
                    lines.append(f"> — *Source: [{cit.title or cit.url}]({cit.url})*")
            if item.tags:
                lines.append(f"> Tags: {', '.join(item.tags)}")
            lines.append("")

    # Remaining gaps
    if pack.gaps:
        lines.append("## Remaining Evidence Gaps")
        lines.append(
            "*These areas need further research or manual verification:*"
        )
        lines.append("")
        for gap in pack.gaps:
            lines.append(f"- **{gap.competitor}** — {gap.category.value}: {gap.description}")
            if gap.suggested_sources:
                lines.append(f"  - Suggested: {', '.join(gap.suggested_sources[:2])}")
        lines.append("")

    # Campaign angles
    if pack.campaign_angles:
        lines.append("## Campaign Angles")
        lines.append(
            "*Actionable campaign strategies based on collected evidence:*"
        )
        lines.append("")
        for i, angle in enumerate(pack.campaign_angles, 1):
            confidence_icon = {"high": "🟢", "medium": "🟡", "low": "🔴"}.get(
                angle.confidence.value, "⚪"
            )
            lines.append(f"### {i}. {confidence_icon} {angle.title}")
            lines.append(f"**Target Weakness:** {angle.target_weakness}")
            lines.append(f"**Description:** {angle.description}")
            lines.append(f"**Channel Fit:** {', '.join(angle.channel_fit)}")
            if angle.supporting_evidence_ids:
                lines.append(
                    f"**Evidence IDs:** {', '.join(angle.supporting_evidence_ids)}"
                )
            lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append(f"- **Total Evidence Items:** {len(pack.evidence)}")
    lines.append(f"- **Remaining Gaps:** {len(pack.gaps)}")
    lines.append(f"- **Campaign Angles Generated:** {len(pack.campaign_angles)}")
    lines.append(f"- **Research Iterations:** {len(pack.iterations)}")
    lines.append(f"- **Coverage Score:** {pack.coverage_score:.1f}%")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Market Intelligence Agent — Campaign+ Enhancement*")

    return "\n".join(lines)
